archiver:
  image: tessarine/intrusion-archiver
  tag: "main"
  replicatcount: "1"
  pullPolicy: Always
  tmpfolder: "tmpvideo"
  s3:
    endpointUrl: "https://datafabric01.ezmeral.demo.hpelabs.fr:9000"
    bucket: "video_archive"
    region: "us-east-1"
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
      nvidia.com/gpu: "0"
    requests:
      cpu: 500m
      memory: 1Gi

detector:
  image: tessarine/intrusion-detector
  tag: "main"
  replicatcount: "1"
  pullPolicy: Always
  kafka:
    bootstrapServers: "datafabric01.ezmeral.demo.hpelabs.fr:9092"
    topic: "object-events"
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
      nvidia.com/gpu: "0"
    requests:
      cpu: 500m
      memory: 1Gi

env:
  roomName: "Server-Room-04"
  cameraRTSPUrl: "rtsp://camera-device-ip:554/stream1"
  confidenceThreshold: "0.75"
