apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intrusion.fullname" . }}-archiver-config
data:
  SRC_FOLDER: {{ .Values.archiver.tmpfolder | quote }}
  S3_ENDPOINT_URL: {{ .Values.archiver.s3.endpointUrl | quote }}
  S3_BUCKET_NAME: {{ .Values.archiver.s3.bucket | quote }}
  S3_REGION: {{ .Values.archiver.s3.region | quote }}
      