apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intrusion.fullname" . }}-archiver
  labels:
    app: {{ include "intrusion.fullname" . }}-archiver
spec:
  replicas: {{ .Values.archiver.replicatcount }}
  selector:
    matchLabels:
      app: {{ include "intrusion.fullname" . }}-archiver
  template:
    metadata:
      labels:
        app: {{ include "intrusion.fullname" . }}-archiver
    spec:
      volumes:
        - name: ca-cert                 
          configMap:
            name: {{ include "intrusion.fullname" . }}-s3
      containers:
        - name: archiver
          image: "{{ .Values.archiver.image }}:{{ .Values.archiver.tag }}"
          imagePullPolicy: {{ .Values.archiver.pullPolicy }}
          args: ["python3", "video_archiver.py"]
          envFrom:
            - configMapRef:
                name: {{ include "intrusion.fullname" . }}-archiver-config
            - secretRef:
                name: {{ include "intrusion.fullname" . }}-s3-secret
          env:                        
            - name: SSL_CERT_FILE
              value: /etc/ssl/custom/ca.crt
            - name: AWS_CA_BUNDLE
              value: /etc/ssl/custom/ca.crt
            - name: AWS_REQUEST_CHECKSUM_CALCULATION
              value: "when_required"
            - name: AWS_RESPONSE_CHECKSUM_VALIDATION
              value: "when_required"
          volumeMounts:
            - mountPath: /etc/ssl/custom
              name: ca-cert
              readOnly: true
          resources:
            {{- toYaml .Values.archiver.resources | nindent 12 -}}