apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intrusion.fullname" . }}-detector
  labels:
    app: {{ include "intrusion.fullname" . }}-detector
spec:
  replicas: {{ .Values.detector.replicatcount }}
  selector:
    matchLabels:
      app: {{ include "intrusion.fullname" . }}-detector
  template:
    metadata:
      labels:
        app: {{ include "intrusion.fullname" . }}-detector
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ include "intrusion.fullname" . }}-pvc 
      containers:
        - name: detector
          image: "{{ .Values.detector.image }}:{{ .Values.detector.tag }}"
          imagePullPolicy: {{ .Values.detector.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "intrusion.fullname" . }}-detector-config
            - secretRef:
                name: {{ include "intrusion.fullname" . }}-s3-secret
          volumeMounts:
            - mountPath: /tmp/videos
              name: shared-storage
          resources:
            {{- toYaml .Values.detector.resources | nindent 12 -}}
