apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intrusion.fullname" . }}-injector
  labels:
    app: {{ include "intrusion.fullname" . }}-i   njector
spec:
  replicas: {{ .Values.injector.replicatcount }}
  selector:
    matchLabels:
      app: {{ include "intrusion.fullname" . }}-injector
  template:
    metadata:
      labels:
        app: {{ include "intrusion.fullname" . }}-injector
    spec:
      containers:
        - name: injector
          image: "{{ .Values.injector.image }}:{{ .Values.injector.tag }}"
          imagePullPolicy: {{ .Values.injector.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "intrusion.fullname" . }}-injector-config
            - secretRef:
                name: {{ include "intrusion.fullname" . }}-s3-secret
          resources:
            {{- toYaml .Values.injector.resources | nindent 12 -}}