apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intrusion.fullname" . }}-s3
data:
  ca.crt: |                      
    -----BEGIN CERTIFICATE-----
    MIIC5jCCAkegAwIBAgIFAJB9VHcwCgYIKoZIzj0EAwIwgYIxEjAQBgoJkiaJk/Is
    ZAEZFgJmcjEXMBUGCgmSJomT8ixkARkWB2hwZWxhYnMxDTALBgNVBAoMBE1hcFIx
    ITAfBgNVBAsMGE1hcFIgRW5naW5lZXJpbmcgUm9vdCBDQTEhMB8GA1UEAwwYTWFw
    UiBFbmdpbmVlcmluZyBSb290IENBMCAXDTI2MDEyNTE1MjgzMloYDzIxMjYwMTAx
    MTUyODMyWjCBgjESMBAGCgmSJomT8ixkARkWAmZyMRcwFQYKCZImiZPyLGQBGRYH
    aHBlbGFiczENMAsGA1UECgwETWFwUjEhMB8GA1UECwwYTWFwUiBFbmdpbmVlcmlu
    ZyBSb290IENBMSEwHwYDVQQDDBhNYXBSIEVuZ2luZWVyaW5nIFJvb3QgQ0EwgZsw
    EAYHKoZIzj0CAQYFK4EEACMDgYYABACQGCHSlz8Amsp1xG7Csj5Xv5+HrTaAPkA8
    wkZM34s61AJEfD7sNNCfEBMtbPzQ+9EgcJ64K80Me6NpoW9gK5XPrwG3UdJStFvR
    P9xN23KPudpcyU+EAdCYzJv2+5pHRVpRIwckNgvMMDOxwUs1PCJw/1iYaXhnU9bv
    ZaiE2Mi7FwKqLKNjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8w
    HQYDVR0OBBYEFCTErUGUELyMaqProRco7OyrjOgCMB8GA1UdIwQYMBaAFCTErUGU
    ELyMaqProRco7OyrjOgCMAoGCCqGSM49BAMCA4GMADCBiAJCAYuNgnXyB5iDV9Bp
    LhvfEZLvjQ0le99yGyKdZIYs3UcTnAaobjdidhQpQy/t8mRm9Z1YItAmhqqZM4kJ
    tR5xM84ZAkIAkAq4w0SyjEogB/oHRXJDARMGpUusEgmX1zNOriDPgkRJWtcgo+Hk
    f03geMJhIDxiHHOVjsp6m8QQQgSYrKca0yw=
    -----END CERTIFICATE-----